import { AdModel } from "../_models/ad.models";
export const ads: AdModel[] = [
    {
        adId: '636671112867386100',
        adTitle: 'Ad 0',
        adContent:
            'Voluptate nisi pariatur et ex aliqua sint ea non laborum velit mollit veniam exercitation quis. Esse nisi ullamco sit eu mollit. Exercitation ipsum est ipsum eiusmod magna. Occaecat aute mollit non laborum proident sint voluptate incididunt duis. Commodo consectetur laborum aliqua do reprehenderit laboris id nostrud. Veniam aliquip culpa sit qui deserunt. Aliquip esse incididunt esse anim officia laboris ut Lorem incididunt dolor.',
        adDisplayDays: 30,
        userIdOrEmail: 'ad0email@live.com',
        userPhoneNumber: '+1 (861) 570-3658',
        userSocialAvatarUrl: 'http://placehold.it/200x200',
        userLoggedInSocialProviderName: 'twitter',
        addressStreet: '871 Hamilton Walk',
        addressCity: 'Sedley',
        addressDistrictOrCounty: 'orange',
        addressState: 'Mississippi',
        addressPartiesMeetingLandmarkName: 'Lena Hawkins',
        addressZipCode: '45298-5298',
        addressCountryCode: 'ca',
        addressCountryName: 'india',
        addressLatitude: -85.985935,
        addressLongitude: -70.188205,
        itemCost: 3720.27,
        itemCostCurrencyName: 'dollar',
        itemCurrencyISO_4217: 'USD',
        attachedAssetsInCloudCount: 0,
        attachedAssetsInCloudStorageId: '8b8174ed-dc5d-4433-b41d-175625bd363d',
        attachedAssetsStoredInCloudBaseFolderPath: 'https://github.com/chinnarao',
        createdDateTime: '2018-10-22T06:06:52+00:00',
        updatedDateTime: '2018-10-22T06:06:52+00:00',
        isDeleted: true,
        deletedDateTime: '',
        isPublished: true,
        lastDraftOrBeforePublishedDateTime: '2018-10-22T06:06:52+00:00',
        lastPublishedDateTime: '2018-10-22T06:06:52+00:00',
        isActive: true,
        lastActiveDateTime: '',
        lastInActiveDateTime: '',
        tag1: 'aliqua',
        tag2: 'anim',
        tag3: 'Lorem',
        tag4: 'sit',
        tag5: 'consectetur',
        tag6: 'labore',
        tag7: 'commodo',
        tag8: 'laborum',
        tag9: 'ea',
        updatedDateTimeString: '2018-10-22T06:06:52+00:00',
        category: null,
        condition: null,
        isBingTypeaheadShow: false,
        isHereTypeaheadShow: false,
        isMapTilerTypeaheadShow: false,
        isGoogleTypeaheadShow: false,
    },
    {
        adId: '636671112867386101',
        adTitle: 'Ad 1',
        adContent:
            'Minim ex sint quis non officia quis excepteur. Nulla ex laborum veniam ex sint ea ad anim aliqua culpa reprehenderit et commodo cupidatat. Duis ea ea velit id aliquip sint laborum. Laboris do id elit dolore et sit consequat consequat exercitation dolor deserunt. Mollit mollit laboris aliquip fugiat sunt est amet fugiat ad qui.',
        adDisplayDays: 30,
        userIdOrEmail: 'ad1email@live.com',
        userPhoneNumber: '+1 (810) 425-3869',
        userSocialAvatarUrl: 'http://placehold.it/200x200',
        userLoggedInSocialProviderName: 'google',
        addressStreet: '530 Hinsdale Street',
        addressCity: 'Whitewater',
        addressDistrictOrCounty: 'anonymous',
        addressState: 'Northern Mariana Islands',
        addressPartiesMeetingLandmarkName: 'Matthews Mcneil',
        addressZipCode: '45785-5785',
        addressCountryCode: 'sl',
        addressCountryName: 'sri lanka',
        addressLatitude: 85.98673,
        addressLongitude: 97.124498,
        itemCost: 1474.36,
        itemCostCurrencyName: 'dollar',
        itemCurrencyISO_4217: 'USD',
        attachedAssetsInCloudCount: 2,
        attachedAssetsInCloudStorageId: '8b8174ed-dc5d-4433-b41d-175625bd363d',
        attachedAssetsStoredInCloudBaseFolderPath: 'https://github.com/chinnarao',
        createdDateTime: '2018-10-22T06:06:52+00:00',
        updatedDateTime: '2018-10-22T06:06:52+00:00',
        isDeleted: true,
        deletedDateTime: '',
        isPublished: false,
        lastDraftOrBeforePublishedDateTime: '2018-10-22T06:06:52+00:00',
        lastPublishedDateTime: '2018-10-22T06:06:52+00:00',
        isActive: true,
        lastActiveDateTime: '',
        lastInActiveDateTime: '',
        tag1: 'do',
        tag2: 'amet',
        tag3: 'nulla',
        tag4: 'aute',
        tag5: 'sint',
        tag6: 'exercitation',
        tag7: 'adipisicing',
        tag8: 'irure',
        tag9: 'nostrud',
        updatedDateTimeString: '2018-10-22T06:06:52+00:00',
        category: null,
        condition: null,
        isBingTypeaheadShow: false,
        isHereTypeaheadShow: false,
        isMapTilerTypeaheadShow: false,
        isGoogleTypeaheadShow: false,
    }
];
